---
name: File-Marker
version: 0.13
author:
  - 'David A. Golden <dagolden@cpan.org>'
abstract: Set and jump between named position markers on a filehandle
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Spec::Functions: 0
  File::Temp: 0.14
  IO::File: 0
  Scalar::Util: 1.09
  Test::More: 0.47
provides:
  File::Marker:
    file: lib/File/Marker.pm
    version: 0.13
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
